// ======================================================
// Sistema de manejo de donaciones de sangre
// ======================================================

syntax = "proto3";

package reservas;

service ReservaService {
    // Consultar tipo de sangre específico y retornar la cantidad disponible respectiva.
    rpc ConsultarTipoSangre(ConsultarTipoRequest) returns (ConsultarTipoResponse);

    // Listar el stock por tipo de sangre.
    rpc ListarStock (ListarStockRequest) returns (ListarStockResponse);

    // Resevar unidades al solicitarlas
    rpc ReservarUnidades (ReservarUnidadesRequest) returns (ReservarUnidadesResponse);

    // Devolver unidades si una solicitud se cancela
    rpc LiberarUnidades (LiberarUnidadesRequest) returns (LiberarUnidadesResponse);
}

enum TipoSangre {
    TIPO_SANGRE_DESCONOCIDO = 0;
    A_POSITIVO = 1;
    A_NEGATIVO = 2;
    B_POSITIVO = 3;
    B_NEGATIVO = 4;
    AB_POSITIVO = 5;
    AB_NEGATIVO = 6;
    O_POSITIVO = 7;
    O_NEGATIVO = 8;
}

message StockSangre {
    TipoSangre tipo_sangre = 1;
    int32 unidades_disponibles = 2;
}

message ConsultarTipoRequest {
    TipoSangre tipo_sangre = 1;
}

message ConsultarTipoResponse {
    TipoSangre tipo_sangre = 1;
    int32 unidades_disponibles = 2;
}

message ListarStockRequest {
    // Agregar a futuro filtros ?
}

message ListarStockResponse {
    repeated StockSangre items = 1;
}

message ReservarUnidadesRequest {
    string id_solicitud = 1;
    TipoSangre tipo_sangre = 2;
    int32 cantidad = 3;
}

message ReservarUnidadesResponse{
    string id_solicitud = 1;
    TipoSangre tipo_sangre = 2;
    int32 unidades_reservadas = 3;
    int32 unidades_restantes = 4;
}

message LiberarUnidadesRequest {
    string id_solicitud = 1;
    TipoSangre tipo_sangre = 2;
    int32 cantidad = 3;
}

message LiberarUnidadesResponse {
    string id_solicitud = 1;
    TipoSangre tipo_sangre = 2;
    int32 unidades_liberadas = 3;
    int32 unidades_restantes = 4;
}
